### ISSUE TITLE
CloutMegazord Audit

### ISSUE THREAD

**Issue by BogdanDidenko** [devaudit/cloutapps#1]
AUDIT REQUEST:

# Project Meta

* PROJECT NAME -- @CloutMegazord
* PROJECT BITCLOUT URL -- https://bitclout.com/u/CloutMegazord
* PROJECT_EXTERNAL_URL -- https://cloutmegazord.com/
* PROJECT TYPE[S]  -- WEB_APPLICATION, AUTH_TYPE_[IDENTITY], AUTH_TYPE_[OTHER]
  * (?) List all types that apply: 
      * $WEB_APPLICATION
      * $CHROME_EXTENSION
      * $NATIVE_APPLICATION_COMPILED_DESKTOP
      * $NATIVE_APPLICATION_COMPILED_MOBILE_IOS[or ANDROID]
      * $AUTH_TYPE_[ IDENTITY|| SELF_SIGN || OTHER || NONE ]

* AUTHOR/REPRESENTATIVE NAME -- Bohdan Didenko
* AUTHOR/REPRESENTATIVE PROJECT AFFILIATION -- $AUTHOR_OR_REP_AFFILIATION
* AUTHOR/REPRESENTATIVE BITCLOUT URL --  https://bitclout.com/u/transhumanist

# Project Detail
'"Multi-Signature" implementation for BitClout. Allows to create and manage accounts jointly by splitting high entropy seed phrase between several owners. Seed phrases by concating on the server. 
https://cloutmegazord.com/landing/home#product

# Auth Implementation
* Do you need bitclout user data? Y (JWT token only for login and part of seed phrase for Megazord managing)

* If yes, describe how you authorize users, or describe where your bitclout backend data is coming from 
(encrypted seeds stored on the database no longer than 10 minutes, encryption key don't stored in database but also provided to server for decryption encrypted seeds before signing transaction)

* Any other means of authenticating clients? (OAuth/SAML/SSO, AD,  Other) 
If yes, describe

## Identity (ID, self signing, etc)
* Do you use BitClout Identity? 
Y

* Access level, and describe usage as much as possible (stored locally, saved in own app backend) 
Access level == 2 JWT only

# AM I SELF SIGNING?
Yes -- My opinion is that the private key cannot be stored anywhere in my implementation, but I need help and a fresh look from outside.

**Comment by Zyther** [comment]
@BogdanDidenko released
